[tool.poetry]
name = "python-prototypes"
version = "0.1.0"
description = ""
authors = ["Vishal Kotak <vishal.sanjiv.kotak@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
elasticsearch = "7.13.0"
python-json-logger = "^3.2.1"
bitarray = "^3.0.0"
mmh3 = "^5.0.1"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
isort = "^5.13.2"
mypy = "^1.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
