version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: foqs_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=foqsdb
      - MYSQL_USER=foqsuser
      - MYSQL_PASSWORD=foqspass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
